/**
 * Downloads the three families from Google Fonts and writes a local @font-face
 * stylesheet, so no page depends on a render-blocking third-party stylesheet.
 * That also keeps EU visitors' addresses away from Google, which the privacy
 * policy already implies by claiming no third-party tracking.
 *
 * Two things keep the generated CSS small. All three families are variable, and
 * Google returns the same file for every weight of a family, so the weights
 * collapse into one @font-face per family and subset carrying a weight range.
 * And only the subsets this site can actually render are kept — note that the
 * hryvnia sign lives in cyrillic-ext, not cyrillic.
 *
 * Run with `npm run fonts`. Output is committed: it is a build input.
 */
import { mkdirSync, rmSync, writeFileSync } from 'node:fs';

const FAMILIES = [
  { name: 'Oswald', css: 'Oswald:wght@400;500;600', weights: '400 600', slug: 'oswald' },
  { name: 'Onest', css: 'Onest:wght@400;500;700', weights: '400 700', slug: 'onest' },
  { name: 'JetBrains Mono', css: 'JetBrains+Mono:wght@500;700', weights: '500 700', slug: 'jetbrains-mono' },
];

const SUBSETS = ['latin', 'latin-ext', 'cyrillic', 'cyrillic-ext'];

// Google serves woff2 only to browsers it recognises; the default fetch UA gets ttf.
const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) ' +
  'Chrome/140.0.0.0 Safari/537.36';

// The files live under src/, not public/, so Vite fingerprints them and applies
// the configured base path. An absolute /assets/ URL in a stylesheet would break
// the GitHub Pages build, which serves the site from /bms-pro/.
const FONT_DIR = 'src/styles/fonts';
const CSS_OUT = 'src/styles/fonts.css';

const CSS_URL =
  'https://fonts.googleapis.com/css2?' +
  FAMILIES.map((f) => `family=${f.css}`).join('&') +
  '&display=swap';

rmSync(FONT_DIR, { recursive: true, force: true });
mkdirSync(FONT_DIR, { recursive: true });

const res = await fetch(CSS_URL, { headers: { 'User-Agent': UA } });
if (!res.ok) throw new Error(`Google Fonts returned ${res.status}`);
const source = await res.text();

/** Google prefixes every @font-face with a `/* subset *\/` comment. */
const blocks = [...source.matchAll(/\/\*\s*([\w-]+)\s*\*\/\s*@font-face\s*\{([\s\S]*?)\}/g)].map(
  ([, subset, body]) => ({
    subset,
    family: body.match(/font-family:\s*'([^']+)'/)[1],
    url: body.match(/url\((https:\/\/fonts\.gstatic\.com\/[^)]+)\)/)[1],
    range: body.match(/unicode-range:\s*([^;]+);/)[1].trim(),
  }),
);
if (blocks.length === 0) throw new Error('no @font-face blocks in the stylesheet');

// One entry per family and subset — the weights all point at the same variable file.
const wanted = new Map();
for (const b of blocks) {
  const family = FAMILIES.find((f) => f.name === b.family);
  if (!family || !SUBSETS.includes(b.subset)) continue;
  wanted.set(`${family.slug}-${b.subset}`, { ...b, family });
}

const css = [];
let bytes = 0;

for (const [slug, b] of [...wanted].sort()) {
  const file = `${slug}.woff2`;
  const buf = Buffer.from(await (await fetch(b.url, { headers: { 'User-Agent': UA } })).arrayBuffer());
  writeFileSync(`${FONT_DIR}/${file}`, buf);
  bytes += buf.length;

  css.push(
    `@font-face{font-family:'${b.family.name}';font-style:normal;` +
      `font-weight:${b.family.weights};font-display:swap;` +
      `src:url(./fonts/${file}) format('woff2');unicode-range:${b.range}}`,
  );
}

writeFileSync(
  CSS_OUT,
  `/* Generated by scripts/fetch-fonts.mjs — do not edit by hand. */\n${css.join('\n')}\n`,
);

const skipped = new Set(blocks.map((b) => b.subset).filter((s) => !SUBSETS.includes(s)));
console.log(`${wanted.size} faces, ${(bytes / 1024).toFixed(0)} KB → ${FONT_DIR}`);
console.log(`skipped subsets: ${[...skipped].sort().join(', ')}`);
console.log(`stylesheet → ${CSS_OUT} (${(Buffer.byteLength(css.join('\n')) / 1024).toFixed(1)} KB)`);
